# Generated by Django 5.2.3 on 2025-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.UUIDField()),
                ('middle_name', models.CharField(max_length=20)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('subject_specialization', models.CharField(max_length=20)),
                ('qualification', models.CharField(choices=[('Degree', 'degree'), ('Master Degree', 'master degree'), ('Phd', 'phd')], default='Degree', max_length=15)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive'), ('On Leave', 'on leave')], default='Active', max_length=10)),
                ('Profile_image', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
