# Generated by Django 5.2.3 on 2025-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Father', 'father'), ('Mother', 'mother'), ('Guardian', 'guardian'), ('Other', 'other')], default='Father', max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('emergency_contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
