# Generated by Django 5.2.3 on 2025-07-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('middle_name', models.CharField(max_length=30)),
                ('admission_date', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('profile_image', models.CharField(max_length=100)),
            ],
        ),
    ]
