# Generated by Django 5.2.3 on 2025-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_uuid', models.UUIDField(unique=True)),
                ('department_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
